# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab3128a33b6a93eba2fb9eb25b54347e4249ca0f0b510f1117f9ce927fdd0dea1f0ad18792913ff7d3fcc0a1d469769ecc7011e0e134b9f8849f2b4a6b3b0706

test:
  secret_key_base: 78168839985fcee1df5868bc6f46ebfa8941191e725b20a4e155b1d56961cefda6ddf2e17918354904fa3a91ef823f945de30461e056e83044ae571f8927d1f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
